"""Add material rejection tracking

Revision ID: 17ae0dbe7d0c
Revises: b9b5be7b372a
Create Date: 2026-01-23 22:40:10.662600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ae0dbe7d0c'
down_revision: Union[str, Sequence[str], None] = 'b9b5be7b372a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rejection_number', sa.String(length=50), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('original_issuance_id', sa.Integer(), nullable=True),
    sa.Column('quantity_rejected', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('rejection_date', sa.Date(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('return_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('received_by', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('warehouse_grn_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['original_issuance_id'], ['material_issuances.id'], ),
    sa.ForeignKeyConstraint(['return_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rejection_number')
    )
    op.create_index('ix_material_rejections_contractor_material', 'material_rejections', ['contractor_id', 'material_id'], unique=False)
    op.create_index(op.f('ix_material_rejections_id'), 'material_rejections', ['id'], unique=False)
    op.create_index('ix_material_rejections_rejection_date', 'material_rejections', ['rejection_date'], unique=False)
    op.create_index('ix_material_rejections_status', 'material_rejections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_material_rejections_status', table_name='material_rejections')
    op.drop_index('ix_material_rejections_rejection_date', table_name='material_rejections')
    op.drop_index(op.f('ix_material_rejections_id'), table_name='material_rejections')
    op.drop_index('ix_material_rejections_contractor_material', table_name='material_rejections')
    op.drop_table('material_rejections')
    # ### end Alembic commands ###
