"""Add audit system models

Revision ID: 362e7e6fca34
Revises: a62d068db52e
Create Date: 2026-01-23 22:53:18.420860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362e7e6fca34'
down_revision: Union[str, Sequence[str], None] = 'a62d068db52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_number', sa.String(length=50), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('auditor_name', sa.String(length=100), nullable=False),
    sa.Column('audit_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_number')
    )
    op.create_index('ix_audits_contractor_date', 'audits', ['contractor_id', 'audit_date'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index('ix_audits_status', 'audits', ['status'], unique=False)
    op.create_table('variance_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('threshold_percentage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'material_id', name='uq_variance_threshold_contractor_material')
    )
    op.create_index(op.f('ix_variance_thresholds_id'), 'variance_thresholds', ['id'], unique=False)
    op.create_table('audit_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('physical_count', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('auditor_notes', sa.Text(), nullable=True),
    sa.Column('expected_quantity', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('variance', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('variance_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('threshold_used', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'material_id', name='uq_audit_line_item_audit_material')
    )
    op.create_index('ix_audit_line_items_audit_id', 'audit_line_items', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_line_items_id'), 'audit_line_items', ['id'], unique=False)
    op.create_index('ix_audit_line_items_is_anomaly', 'audit_line_items', ['is_anomaly'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjustment_number', sa.String(length=50), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('audit_line_item_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('adjustment_quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['audit_line_item_id'], ['audit_line_items.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_number')
    )
    op.create_index('ix_inventory_adjustments_contractor_material', 'inventory_adjustments', ['contractor_id', 'material_id'], unique=False)
    op.create_index('ix_inventory_adjustments_date', 'inventory_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_id'), 'inventory_adjustments', ['id'], unique=False)
    op.create_index('ix_inventory_adjustments_status', 'inventory_adjustments', ['status'], unique=False)
    op.create_index('ix_inventory_adjustments_type', 'inventory_adjustments', ['adjustment_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_adjustments_type', table_name='inventory_adjustments')
    op.drop_index('ix_inventory_adjustments_status', table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_id'), table_name='inventory_adjustments')
    op.drop_index('ix_inventory_adjustments_date', table_name='inventory_adjustments')
    op.drop_index('ix_inventory_adjustments_contractor_material', table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index('ix_audit_line_items_is_anomaly', table_name='audit_line_items')
    op.drop_index(op.f('ix_audit_line_items_id'), table_name='audit_line_items')
    op.drop_index('ix_audit_line_items_audit_id', table_name='audit_line_items')
    op.drop_table('audit_line_items')
    op.drop_index(op.f('ix_variance_thresholds_id'), table_name='variance_thresholds')
    op.drop_table('variance_thresholds')
    op.drop_index('ix_audits_status', table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index('ix_audits_contractor_date', table_name='audits')
    op.drop_table('audits')
    # ### end Alembic commands ###
