"""add warehouse inventory table

Revision ID: 38af95f86d09
Revises: ae3862d6a309
Create Date: 2026-01-23 15:08:41.018628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38af95f86d09'
down_revision: Union[str, Sequence[str], None] = 'ae3862d6a309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'material_id', name='uq_warehouse_material')
    )
    op.create_index(op.f('ix_warehouse_inventory_id'), 'warehouse_inventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_inventory_id'), table_name='warehouse_inventory')
    op.drop_table('warehouse_inventory')
    # ### end Alembic commands ###
