"""Add reconciliation system

Revision ID: 3b2172e10f19
Revises: 362e7e6fca34
Create Date: 2026-01-24 10:02:00.073264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2172e10f19'
down_revision: Union[str, Sequence[str], None] = '362e7e6fca34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_number', sa.String(length=50), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_number')
    )
    op.create_index('ix_reconciliations_contractor_date', 'reconciliations', ['contractor_id', 'reconciliation_date'], unique=False)
    op.create_index(op.f('ix_reconciliations_id'), 'reconciliations', ['id'], unique=False)
    op.create_index('ix_reconciliations_period', 'reconciliations', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_reconciliations_status', 'reconciliations', ['status'], unique=False)
    op.create_table('reconciliation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('reported_quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('contractor_notes', sa.Text(), nullable=True),
    sa.Column('system_quantity', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('variance', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('variance_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('threshold_used', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_id', 'material_id', name='uq_reconciliation_line_recon_material')
    )
    op.create_index(op.f('ix_reconciliation_lines_id'), 'reconciliation_lines', ['id'], unique=False)
    op.create_index('ix_reconciliation_lines_is_anomaly', 'reconciliation_lines', ['is_anomaly'], unique=False)
    op.create_index('ix_reconciliation_lines_reconciliation_id', 'reconciliation_lines', ['reconciliation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reconciliation_lines_reconciliation_id', table_name='reconciliation_lines')
    op.drop_index('ix_reconciliation_lines_is_anomaly', table_name='reconciliation_lines')
    op.drop_index(op.f('ix_reconciliation_lines_id'), table_name='reconciliation_lines')
    op.drop_table('reconciliation_lines')
    op.drop_index('ix_reconciliations_status', table_name='reconciliations')
    op.drop_index('ix_reconciliations_period', table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_id'), table_name='reconciliations')
    op.drop_index('ix_reconciliations_contractor_date', table_name='reconciliations')
    op.drop_table('reconciliations')
    # ### end Alembic commands ###
