"""add_finished_goods_and_production_records

Revision ID: 3db47501d1c8
Revises: ee76a7d1a6b6
Create Date: 2026-01-16 00:02:18.663436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db47501d1c8'
down_revision: Union[str, Sequence[str], None] = 'ee76a7d1a6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_goods_code'), 'finished_goods', ['code'], unique=True)
    op.create_index(op.f('ix_finished_goods_id'), 'finished_goods', ['id'], unique=False)
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('finished_good_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('production_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['finished_good_id'], ['finished_goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_id'), 'production_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_records_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_finished_goods_id'), table_name='finished_goods')
    op.drop_index(op.f('ix_finished_goods_code'), table_name='finished_goods')
    op.drop_table('finished_goods')
    # ### end Alembic commands ###
