"""add_bom_and_consumption

Revision ID: 7561e89e955c
Revises: 3db47501d1c8
Create Date: 2026-01-16 00:08:32.899666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7561e89e955c'
down_revision: Union[str, Sequence[str], None] = '3db47501d1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_good_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['finished_good_id'], ['finished_goods.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finished_good_id', 'material_id', name='uq_bom_fg_material')
    )
    op.create_index(op.f('ix_bom_id'), 'bom', ['id'], unique=False)
    op.create_table('consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_record_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['production_record_id'], ['production_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_id'), 'consumption', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumption_id'), table_name='consumption')
    op.drop_table('consumption')
    op.drop_index(op.f('ix_bom_id'), table_name='bom')
    op.drop_table('bom')
    # ### end Alembic commands ###
