"""Add material issuance transaction log

Revision ID: b9b5be7b372a
Revises: 41d2a83749d5
Create Date: 2026-01-23 22:24:51.542293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b5be7b372a'
down_revision: Union[str, Sequence[str], None] = '41d2a83749d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_issuances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuance_number', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('quantity_in_base_unit', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('base_unit', sa.String(length=20), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('issued_by', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuance_number')
    )
    op.create_index('ix_material_issuances_contractor_material_date', 'material_issuances', ['contractor_id', 'material_id', 'issued_date'], unique=False)
    op.create_index(op.f('ix_material_issuances_id'), 'material_issuances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_issuances_id'), table_name='material_issuances')
    op.drop_index('ix_material_issuances_contractor_material_date', table_name='material_issuances')
    op.drop_table('material_issuances')
    # ### end Alembic commands ###
