"""add_resolved_to_anomalies

Revision ID: e1b5f9deae54
Revises: 54e8b4c7f782
Create Date: 2026-01-16 15:30:38.158165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b5f9deae54'
down_revision: Union[str, Sequence[str], None] = '54e8b4c7f782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomalies', sa.Column('resolved', sa.Boolean(), nullable=False))
    op.add_column('anomalies', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomalies', 'resolved_at')
    op.drop_column('anomalies', 'resolved')
    # ### end Alembic commands ###
