"""add unit conversions table

Revision ID: f3a027b4d425
Revises: 38af95f86d09
Create Date: 2026-01-23 15:10:35.606668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a027b4d425'
down_revision: Union[str, Sequence[str], None] = '38af95f86d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('from_unit', sa.String(length=20), nullable=False),
    sa.Column('to_unit', sa.String(length=20), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'from_unit', 'to_unit', name='uq_material_unit_conversion')
    )
    op.create_index(op.f('ix_unit_conversions_id'), 'unit_conversions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_conversions_id'), table_name='unit_conversions')
    op.drop_table('unit_conversions')
    # ### end Alembic commands ###
